name: pyscreener

channels:
  - hcc
  - conda-forge
  - defaults

dependencies:
  - pdbfixer
  - pip
  - python=3.8
  - openbabel
  - openmm
  - rdkit
  - adfr-suite
  - pip:
    - colorama
    - configargparse
    - h5py
    - numpy
    - ray
    - pandas
    - scikit_learn
    - scipy
    - tqdm

