name: pyscreener

channels:
  - omnia
  - conda-forge
  - defaults

dependencies:
  - hdf5
  - importlib_resources
  - mpi4py
  - pandas
  - pdbfixer
  - pip
  - plotly
  - python
  - rdkit
  - retrying
  - scikit-learn
  - scipy
  - tqdm