name: pyscreener

channels:
  - conda-forge
  - defaults

dependencies:
  - hdf5
  - importlib_resources
  - mpi4py
  - openbabel
  - pandas
  - omnia::pdbfixer
  - pip
  - plotly
  - python=3.6
  - rdkit=2020.3.05
  - retrying
  - scikit-learn
  - scipy
  - tqdm